package vectorgen

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/Eyevinn/locmaf"
)

// readmeName is the top-level, per-corpus documentation file. It is
// derived from the case matrix (not committed by hand) so it stays
// pinned by Check like every other vector file.
const readmeName = "README.md"

// caseSummary is the per-case row rendered into the corpus README.
type caseSummary struct {
	name        string
	description string
	groups      int
	objects     int
	hasFile     bool // case emits a self-framed file.locmaf
}

// summarize extracts the README row for one case from its generated
// files (counts come straight from the case manifest).
func summarize(c vectorCase, files map[string][]byte) caseSummary {
	var m Manifest
	// manifest.json is produced by generateCase and always valid JSON.
	_ = json.Unmarshal(files["manifest.json"], &m)
	_, hasFile := files["file.locmaf"]
	return caseSummary{
		name:        c.name,
		description: c.description,
		groups:      m.Groups,
		objects:     m.Objects,
		hasFile:     hasFile,
	}
}

// corpusReadme renders the top-level README.md documenting the corpus
// layout and indexing every case. Output is deterministic (cases() is
// ordered) so Check can byte-compare it against disk.
func corpusReadme(summaries []caseSummary) []byte {
	var totalObjects, filesWithLocmaf int
	for _, s := range summaries {
		totalObjects += s.objects
		if s.hasFile {
			filesWithLocmaf++
		}
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# LOCMAF golden vectors\n\n")
	fmt.Fprintf(&b, "<!-- Generated by `locmaf vectors gen`; do not edit by hand. -->\n\n")
	fmt.Fprintf(&b,
		"Codec-derived conformance corpus for LOCMAF packaging version `%s`\n"+
			"(draft commit `%s`). Every file here is regenerated from the\n"+
			"reference codec and byte-pinned by `locmaf vectors check` (run in\n"+
			"CI), so the corpus can never drift from the implementation.\n\n",
		locmaf.Version, draftCommit)

	fmt.Fprintf(&b, "## Regenerating and checking\n\n")
	fmt.Fprintf(&b, "```sh\n")
	fmt.Fprintf(&b, "locmaf vectors gen [-out dir]   # rewrite the corpus from the codec\n")
	fmt.Fprintf(&b, "locmaf vectors check [dir]      # re-derive and byte-compare against disk\n")
	fmt.Fprintf(&b, "```\n\n")
	fmt.Fprintf(&b,
		"Each case lives in its own directory. Within a case, files are named\n"+
			"`gNNN_oNNN`, where `gNNN` is the group index and `oNNN` the object\n"+
			"index within that group.\n\n")

	fmt.Fprintf(&b, "## Files in each case\n\n")
	fmt.Fprintf(&b, "| Path | Contents |\n")
	fmt.Fprintf(&b, "| ---- | -------- |\n")
	fmt.Fprintf(&b, "| `manifest.json` | Case metadata and the SHA-256 of every file in the case. |\n")
	fmt.Fprintf(&b, "| `init.mp4` | The CMAF init segment (`ftyp`+`moov`) the objects decode against. |\n")
	fmt.Fprintf(&b, "| `objects/gNNN_oNNN.locmafobj` | One bare LOCMAF Object — exactly the MOQT object payload, unframed. |\n")
	fmt.Fprintf(&b, "| `canonical/gNNN_oNNN.cmfc` | The byte-exact canonical CMAF chunk reconstructed from that object. |\n")
	fmt.Fprintf(&b, "| `effective/gNNN_oNNN.json` | The decoded effective values (sample durations, sizes, flags, CTOs, CENC aux, gen boxes). |\n")
	fmt.Fprintf(&b, "| `file.locmaf` | *(select cases)* The self-framed, self-contained file: "+
		"vi64 length-prefixed Objects led by an in-band `rawBoxes` init. |\n\n")

	locmafClause := fmt.Sprintf("%d cases emit", filesWithLocmaf)
	if filesWithLocmaf == 1 {
		locmafClause = "1 case emits"
	}
	fmt.Fprintf(&b, "## Cases\n\n")
	fmt.Fprintf(&b, "%d cases, %d objects; %s a self-framed `file.locmaf`.\n\n",
		len(summaries), totalObjects, locmafClause)
	fmt.Fprintf(&b, "| Case | Groups | Objects | `file.locmaf` | Description |\n")
	fmt.Fprintf(&b, "| ---- | -----: | ------: | :-----------: | ----------- |\n")
	for _, s := range summaries {
		mark := ""
		if s.hasFile {
			mark = "✓"
		}
		fmt.Fprintf(&b, "| `%s` | %d | %d | %s | %s |\n",
			s.name, s.groups, s.objects, mark, s.description)
	}

	return []byte(b.String())
}
